### ISSUE TITLE
mame creates folders cfg and nvram in the home dir

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame2010-libretro#14] opened 2015-11-25 18:36 UTC
It's quite annoying, this mame core creates cfg and nvram folders in your ~/ or in the folder you launch RA in the terminal.

**Comment by markwkidd** [comment] 2017-10-04 03:02
@sergiobenrocha2 is this still the case with mame2010?

**Comment by sergiobenrocha2** [comment] 2017-10-05 00:42
yup

**Comment by raelgc** [comment] 2017-11-24 17:52
I've found the reason for this issue: `mame.ini` is located at `/opt/retropie/libretrocores/lr-mame2010/`, but EmulationStation is launching from home folder.

So, I made the following:

1. Moved `mame.ini` to my home folder.

2. Changed, in `mame.ini`, values from `cfg` and `nvram` paths to match `mame2003`. I.e., change from this:

```
#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             cfg
nvram_directory           nvram
```
to this:
```
#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             RetroPie/roms/mame-libretro/mame2010/cfg
nvram_directory           RetroPie/roms/mame-libretro/mame2010/nvram
```

**Comment by markwkidd** [comment] 2017-11-24 18:22
It does seem like this should work by default like mame2003, which handles this more gracefully and in a cross-platform manner.

**Comment by raelgc** [comment] 2017-11-24 18:54
mame2003 takes, by default, the current rom folder to create the `mame2003` folder (with `cfg`, `nvram` and all related subfolders).

So, if you're using mame under `roms/arcade`, you'll get `roms/arcade/mame2003/`, if you're using mame under `roms/libretro-mame`, you'll get `roms/libretro-mame/mame2003/`.

**Comment by movisman** [comment] 2018-02-10 12:42
@raelgc 

Hi there,

Thanks for posting this workaround. So just to confirm, until the core is changed so the paths are more graceful, with your workaround, ultimately you end up with a mame.ini in your home folder, and then the other cfg and nvram paths in the more conventional place? And MAME no longer ignores the .ini for games like Operation Thunderbolt?

Thanks!

**Comment by movisman** [comment] 2018-02-10 16:08
@raelgc 

Perfect! Thanks a lot for the clarification. I will do this with my MAME 2010 instance to tidy things up a tad, until such a time comes where the paths are properly tidied up.

Thanks again!

**Comment by markwkidd** [comment] 2018-02-17 04:00
@sergiobenrocha2 or others in this discussion, I've submitted a PR that I hope addresses this issue and others caused by the way mame2010 handles paths: https://github.com/libretro/mame2010-libretro/pull/83

I wound up touching several different source files. It all seems to work on my system but if you have the ability to test it out and confirm I'd appreciate it.

**Comment by markwkidd** [comment] 2018-02-21 19:10
@sergiobenrocha2 the PRs have been merged and I am hoping that this issue is now fully resolved. Please let me know if you notice other problems.

**Closed** 2018-03-11 15:09 UTC
