### ISSUE TITLE
nagscreenpatch_enable

### ISSUE THREAD

**Issue by Expello** [libretro/mame2010-libretro#16] opened 2016-04-13 14:21 UTC
Hello,
the core option (nagscreenpatch_enable) does not work, I have entered in the mame.ini and in retroarch config, but the "NAG SCREENS" are still displayed.

I use this line:
`mame_current_nagscreenpatch_enable = "enabled"`

There is another way? 
Or how can I change the UI.C in so far as that disappear the "NAG SCREENS"?

Thanks a lot

R-PI 3 / RetroPie 3.6

**Comment by dankcushions** [comment] 2016-04-13 14:54
nagscreenpatch_enable doesn't appear to be actually used in the code, so it looks like this option doesn't really do anything at the moment. a code change is required.

**Comment by Enverex** [comment] 2016-07-15 09:09
I can probably code this back in as I've done with the current and 2014 core if there's still interest?

**Comment by markwkidd** [comment] 2016-07-16 14:07
I'm interested.

**Comment by Enverex** [comment] 2016-07-17 18:56
Ok, I've coded this in but can't test it as I don't have a suitable ROMset. If you'd like to try it, please compile and use this branch https://github.com/Enverex/mame2010-libretro/tree/patch-1 and let me know how you get on.

**Comment by Enverex** [comment] 2016-07-20 00:26
Merged in here - https://github.com/libretro/mame2010-libretro/pull/17

Can you test and report back please.

**Comment by markwkidd** [comment] 2016-07-21 17:08
Is there any chance you could compile a core I can place into a generic x64 Lakka PC installation? I have access to a 0.139 ROM set but I have not compiled any software in more than ten years I'm afraid.

I could probably also put together a windows retroarch environment to test this with if that would be easier for you to build a core for.

**Comment by markwkidd** [comment] 2016-07-21 17:14
Actually, why not check it with one of the MAME ROMs that has been authorized for distribution? You don't need a full ROM set, just one.

This ROM file should give the nag screen in regular MAME 0.139 but not with your patch: http://mamedev.org/roms/robotbwl/

**Comment by Enverex** [comment] 2016-07-21 17:36
It segfaults for me unfortunately. I have a feeling that whilst it now compiles with GCC6.1, it still doesn't produce something usable. I don't have an earlier version of GCC available to compile it with so I can't really check if that's truly the cause.

**Comment by Enverex** [comment] 2016-07-21 17:37
Scratch that, just finished compiling it with GCC 5.4. Will test now.

**Comment by Enverex** [comment] 2016-07-21 17:55
Yep, works perfectly (you need to enable these options under Quick Menu > Options first.

Looks like it still segfaults under GCC6, but at least it builds now so it's slightly less broken in that regard.

**Comment by markwkidd** [comment] 2016-07-22 23:42
Thank you! I'll be experimenting with this core once your patch makes it to the buildbot. If there's anything I can do as a technical writer, RetroArch MAME playlist scripter, or as a person somewhat familiar with the MAME ROM set universe, please let me know.

**Comment by twinaphex** [comment] 2016-12-09 08:15
Nagscreen should now be permanently disabled.

**Closed by twinaphex** 2016-12-09 08:15 UTC
